services:
  # --- Service 1: Database PostgreSQL 15 ---
  db:
    image: postgres:15-alpine
    container_name: moodle_db
    restart: always
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodleuser
      POSTGRES_PASSWORD: Anhmeow123
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  # --- Service 2: Moodle App (PHP 8.2) ---
  web:
    build: .
    container_name: moodle_app
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./moodle_data:/var/www/moodledata
    environment:
      - MOODLE_DB_TYPE=pgsql
      - MOODLE_DB_HOST=db
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodleuser
      - MOODLE_DB_PASSWORD=Anhmeow123
    depends_on:
      - db